/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAssistantRouteImport } from './routes/$lang.assistant'
import { Route as LangAuthRouteImport } from './routes/$lang.auth'
import { Route as LangBusinessRouteImport } from './routes/$lang.business'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedBookCardIdRouteImport } from './routes/_authenticated/book.$cardId'
import { Route as AuthenticatedDevStatusRouteImport } from './routes/_authenticated/dev.status'
import { Route as ApiPublicGetawayPricesRouteImport } from './routes/api/public/getaway-prices'
import { Route as ApiPublicTripRemindersRouteImport } from './routes/api/public/trip-reminders'
import { Route as ApiTripParseRouteImport } from './routes/api/trip/parse'
import { Route as ApiTripPriceContextRouteImport } from './routes/api/trip/price-context'
import { Route as ApiTripSearchRouteImport } from './routes/api/trip/search'
import { Route as ApiPublicCalendarCallbackProviderRouteImport } from './routes/api/public/calendar/callback.$provider'
import { Route as ApiPublicCalendarFeedTokenRouteImport } from './routes/api/public/calendar/feed.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAssistantRoute = LangAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)
const LangBusinessRoute = LangBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => LangRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookCardIdRoute = AuthenticatedBookCardIdRouteImport.update({
  id: '/book/$cardId',
  path: '/book/$cardId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevStatusRoute = AuthenticatedDevStatusRouteImport.update({
  id: '/dev/status',
  path: '/dev/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGetawayPricesRoute = ApiPublicGetawayPricesRouteImport.update({
  id: '/api/public/getaway-prices',
  path: '/api/public/getaway-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTripRemindersRoute = ApiPublicTripRemindersRouteImport.update({
  id: '/api/public/trip-reminders',
  path: '/api/public/trip-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripParseRoute = ApiTripParseRouteImport.update({
  id: '/api/trip/parse',
  path: '/api/trip/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripPriceContextRoute = ApiTripPriceContextRouteImport.update({
  id: '/api/trip/price-context',
  path: '/api/trip/price-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripSearchRoute = ApiTripSearchRouteImport.update({
  id: '/api/trip/search',
  path: '/api/trip/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalendarCallbackProviderRoute =
  ApiPublicCalendarCallbackProviderRouteImport.update({
    id: '/api/public/calendar/callback/$provider',
    path: '/api/public/calendar/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarFeedTokenRoute =
  ApiPublicCalendarFeedTokenRouteImport.update({
    id: '/api/public/calendar/feed/$token',
    path: '/api/public/calendar/feed/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/$lang/assistant': typeof LangAssistantRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/business': typeof LangBusinessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/book/$cardId': typeof AuthenticatedBookCardIdRoute
  '/dev/status': typeof AuthenticatedDevStatusRoute
  '/api/public/getaway-prices': typeof ApiPublicGetawayPricesRoute
  '/api/public/trip-reminders': typeof ApiPublicTripRemindersRoute
  '/api/trip/parse': typeof ApiTripParseRoute
  '/api/trip/price-context': typeof ApiTripPriceContextRoute
  '/api/trip/search': typeof ApiTripSearchRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/calendar/callback/$provider': typeof ApiPublicCalendarCallbackProviderRoute
  '/api/public/calendar/feed/$token': typeof ApiPublicCalendarFeedTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/$lang/assistant': typeof LangAssistantRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/business': typeof LangBusinessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/$lang': typeof LangIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/book/$cardId': typeof AuthenticatedBookCardIdRoute
  '/dev/status': typeof AuthenticatedDevStatusRoute
  '/api/public/getaway-prices': typeof ApiPublicGetawayPricesRoute
  '/api/public/trip-reminders': typeof ApiPublicTripRemindersRoute
  '/api/trip/parse': typeof ApiTripParseRoute
  '/api/trip/price-context': typeof ApiTripPriceContextRoute
  '/api/trip/search': typeof ApiTripSearchRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/calendar/callback/$provider': typeof ApiPublicCalendarCallbackProviderRoute
  '/api/public/calendar/feed/$token': typeof ApiPublicCalendarFeedTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$lang': typeof LangRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/$lang/assistant': typeof LangAssistantRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/business': typeof LangBusinessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/$lang/': typeof LangIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/book/$cardId': typeof AuthenticatedBookCardIdRoute
  '/_authenticated/dev/status': typeof AuthenticatedDevStatusRoute
  '/api/public/getaway-prices': typeof ApiPublicGetawayPricesRoute
  '/api/public/trip-reminders': typeof ApiPublicTripRemindersRoute
  '/api/trip/parse': typeof ApiTripParseRoute
  '/api/trip/price-context': typeof ApiTripPriceContextRoute
  '/api/trip/search': typeof ApiTripSearchRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/calendar/callback/$provider': typeof ApiPublicCalendarCallbackProviderRoute
  '/api/public/calendar/feed/$token': typeof ApiPublicCalendarFeedTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/$lang/assistant'
    | '/$lang/auth'
    | '/$lang/business'
    | '/dashboard'
    | '/invoices'
    | '/onboarding'
    | '/plan'
    | '/preferences'
    | '/trips'
    | '/$lang/'
    | '/admin/analytics'
    | '/admin/payments'
    | '/book/$cardId'
    | '/dev/status'
    | '/api/public/getaway-prices'
    | '/api/public/trip-reminders'
    | '/api/trip/parse'
    | '/api/trip/price-context'
    | '/api/trip/search'
    | '/admin/'
    | '/api/public/calendar/callback/$provider'
    | '/api/public/calendar/feed/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/$lang/assistant'
    | '/$lang/auth'
    | '/$lang/business'
    | '/dashboard'
    | '/invoices'
    | '/onboarding'
    | '/plan'
    | '/preferences'
    | '/trips'
    | '/$lang'
    | '/admin/analytics'
    | '/admin/payments'
    | '/book/$cardId'
    | '/dev/status'
    | '/api/public/getaway-prices'
    | '/api/public/trip-reminders'
    | '/api/trip/parse'
    | '/api/trip/price-context'
    | '/api/trip/search'
    | '/admin'
    | '/api/public/calendar/callback/$provider'
    | '/api/public/calendar/feed/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$lang'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/$lang/assistant'
    | '/$lang/auth'
    | '/$lang/business'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/onboarding'
    | '/_authenticated/plan'
    | '/_authenticated/preferences'
    | '/_authenticated/trips'
    | '/$lang/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/payments'
    | '/_authenticated/book/$cardId'
    | '/_authenticated/dev/status'
    | '/api/public/getaway-prices'
    | '/api/public/trip-reminders'
    | '/api/trip/parse'
    | '/api/trip/price-context'
    | '/api/trip/search'
    | '/_authenticated/admin/'
    | '/api/public/calendar/callback/$provider'
    | '/api/public/calendar/feed/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LangRoute: typeof LangRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  ApiPublicGetawayPricesRoute: typeof ApiPublicGetawayPricesRoute
  ApiPublicTripRemindersRoute: typeof ApiPublicTripRemindersRoute
  ApiTripParseRoute: typeof ApiTripParseRoute
  ApiTripPriceContextRoute: typeof ApiTripPriceContextRoute
  ApiTripSearchRoute: typeof ApiTripSearchRoute
  ApiPublicCalendarCallbackProviderRoute: typeof ApiPublicCalendarCallbackProviderRoute
  ApiPublicCalendarFeedTokenRoute: typeof ApiPublicCalendarFeedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/assistant': {
      id: '/$lang/assistant'
      path: '/assistant'
      fullPath: '/$lang/assistant'
      preLoaderRoute: typeof LangAssistantRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/business': {
      id: '/$lang/business'
      path: '/business'
      fullPath: '/$lang/business'
      preLoaderRoute: typeof LangBusinessRouteImport
      parentRoute: typeof LangRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$cardId': {
      id: '/_authenticated/book/$cardId'
      path: '/book/$cardId'
      fullPath: '/book/$cardId'
      preLoaderRoute: typeof AuthenticatedBookCardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/status': {
      id: '/_authenticated/dev/status'
      path: '/dev/status'
      fullPath: '/dev/status'
      preLoaderRoute: typeof AuthenticatedDevStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/getaway-prices': {
      id: '/api/public/getaway-prices'
      path: '/api/public/getaway-prices'
      fullPath: '/api/public/getaway-prices'
      preLoaderRoute: typeof ApiPublicGetawayPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trip-reminders': {
      id: '/api/public/trip-reminders'
      path: '/api/public/trip-reminders'
      fullPath: '/api/public/trip-reminders'
      preLoaderRoute: typeof ApiPublicTripRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip/parse': {
      id: '/api/trip/parse'
      path: '/api/trip/parse'
      fullPath: '/api/trip/parse'
      preLoaderRoute: typeof ApiTripParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip/price-context': {
      id: '/api/trip/price-context'
      path: '/api/trip/price-context'
      fullPath: '/api/trip/price-context'
      preLoaderRoute: typeof ApiTripPriceContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip/search': {
      id: '/api/trip/search'
      path: '/api/trip/search'
      fullPath: '/api/trip/search'
      preLoaderRoute: typeof ApiTripSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/callback/$provider': {
      id: '/api/public/calendar/callback/$provider'
      path: '/api/public/calendar/callback/$provider'
      fullPath: '/api/public/calendar/callback/$provider'
      preLoaderRoute: typeof ApiPublicCalendarCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/feed/$token': {
      id: '/api/public/calendar/feed/$token'
      path: '/api/public/calendar/feed/$token'
      fullPath: '/api/public/calendar/feed/$token'
      preLoaderRoute: typeof ApiPublicCalendarFeedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedBookCardIdRoute: typeof AuthenticatedBookCardIdRoute
  AuthenticatedDevStatusRoute: typeof AuthenticatedDevStatusRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedBookCardIdRoute: AuthenticatedBookCardIdRoute,
  AuthenticatedDevStatusRoute: AuthenticatedDevStatusRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LangRouteChildren {
  LangAssistantRoute: typeof LangAssistantRoute
  LangAuthRoute: typeof LangAuthRoute
  LangBusinessRoute: typeof LangBusinessRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAssistantRoute: LangAssistantRoute,
  LangAuthRoute: LangAuthRoute,
  LangBusinessRoute: LangBusinessRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LangRoute: LangRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  ApiPublicGetawayPricesRoute: ApiPublicGetawayPricesRoute,
  ApiPublicTripRemindersRoute: ApiPublicTripRemindersRoute,
  ApiTripParseRoute: ApiTripParseRoute,
  ApiTripPriceContextRoute: ApiTripPriceContextRoute,
  ApiTripSearchRoute: ApiTripSearchRoute,
  ApiPublicCalendarCallbackProviderRoute:
    ApiPublicCalendarCallbackProviderRoute,
  ApiPublicCalendarFeedTokenRoute: ApiPublicCalendarFeedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
