/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangAssistantRouteImport } from './routes/$lang.assistant'
import { Route as LangAuthRouteImport } from './routes/$lang.auth'
import { Route as LangBusinessRouteImport } from './routes/$lang.business'
import { Route as AuthenticatedCreatorRouteImport } from './routes/_authenticated/creator'
import { Route as AuthenticatedCreditRouteImport } from './routes/_authenticated/credit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGetawayRouteImport } from './routes/_authenticated/getaway'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as CHandleRouteImport } from './routes/c.$handle'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminCreatorsRouteImport } from './routes/_authenticated/admin.creators'
import { Route as AuthenticatedAdminGetawayRouteImport } from './routes/_authenticated/admin.getaway'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedBookCardIdRouteImport } from './routes/_authenticated/book.$cardId'
import { Route as AuthenticatedCreatorsApplyRouteImport } from './routes/_authenticated/creators.apply'
import { Route as AuthenticatedDevStatusRouteImport } from './routes/_authenticated/dev.status'
import { Route as ApiPublicGetawayPricesRouteImport } from './routes/api/public/getaway-prices'
import { Route as ApiPublicGetawayWeeklyRouteImport } from './routes/api/public/getaway-weekly'
import { Route as ApiPublicTripRemindersRouteImport } from './routes/api/public/trip-reminders'
import { Route as ApiTripParseRouteImport } from './routes/api/trip/parse'
import { Route as ApiTripPriceContextRouteImport } from './routes/api/trip/price-context'
import { Route as ApiTripSearchRouteImport } from './routes/api/trip/search'
import { Route as ApiPublicGetawayImageSplatRouteImport } from './routes/api/public/getaway-image.$'
import { Route as ApiPublicSupplierOrderUpdatedRouteImport } from './routes/api/public/supplier/order-updated'
import { Route as ApiPublicCalendarCallbackProviderRouteImport } from './routes/api/public/calendar/callback.$provider'
import { Route as ApiPublicCalendarFeedTokenRouteImport } from './routes/api/public/calendar/feed.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAssistantRoute = LangAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => LangRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRoute,
} as any)
const LangBusinessRoute = LangBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => LangRoute,
} as any)
const AuthenticatedCreatorRoute = AuthenticatedCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditRoute = AuthenticatedCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGetawayRoute = AuthenticatedGetawayRouteImport.update({
  id: '/getaway',
  path: '/getaway',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CHandleRoute = CHandleRouteImport.update({
  id: '/c/$handle',
  path: '/c/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCreatorsRoute =
  AuthenticatedAdminCreatorsRouteImport.update({
    id: '/admin/creators',
    path: '/admin/creators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGetawayRoute =
  AuthenticatedAdminGetawayRouteImport.update({
    id: '/admin/getaway',
    path: '/admin/getaway',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookCardIdRoute = AuthenticatedBookCardIdRouteImport.update({
  id: '/book/$cardId',
  path: '/book/$cardId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorsApplyRoute =
  AuthenticatedCreatorsApplyRouteImport.update({
    id: '/creators/apply',
    path: '/creators/apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevStatusRoute = AuthenticatedDevStatusRouteImport.update({
  id: '/dev/status',
  path: '/dev/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGetawayPricesRoute = ApiPublicGetawayPricesRouteImport.update({
  id: '/api/public/getaway-prices',
  path: '/api/public/getaway-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetawayWeeklyRoute = ApiPublicGetawayWeeklyRouteImport.update({
  id: '/api/public/getaway-weekly',
  path: '/api/public/getaway-weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTripRemindersRoute = ApiPublicTripRemindersRouteImport.update({
  id: '/api/public/trip-reminders',
  path: '/api/public/trip-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripParseRoute = ApiTripParseRouteImport.update({
  id: '/api/trip/parse',
  path: '/api/trip/parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripPriceContextRoute = ApiTripPriceContextRouteImport.update({
  id: '/api/trip/price-context',
  path: '/api/trip/price-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTripSearchRoute = ApiTripSearchRouteImport.update({
  id: '/api/trip/search',
  path: '/api/trip/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetawayImageSplatRoute =
  ApiPublicGetawayImageSplatRouteImport.update({
    id: '/api/public/getaway-image/$',
    path: '/api/public/getaway-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSupplierOrderUpdatedRoute =
  ApiPublicSupplierOrderUpdatedRouteImport.update({
    id: '/api/public/supplier/order-updated',
    path: '/api/public/supplier/order-updated',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarCallbackProviderRoute =
  ApiPublicCalendarCallbackProviderRouteImport.update({
    id: '/api/public/calendar/callback/$provider',
    path: '/api/public/calendar/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarFeedTokenRoute =
  ApiPublicCalendarFeedTokenRouteImport.update({
    id: '/api/public/calendar/feed/$token',
    path: '/api/public/calendar/feed/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$lang/assistant': typeof LangAssistantRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/business': typeof LangBusinessRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/credit': typeof AuthenticatedCreditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/getaway': typeof AuthenticatedGetawayRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/c/$handle': typeof CHandleRoute
  '/r/$code': typeof RCodeRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/getaway': typeof AuthenticatedAdminGetawayRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/book/$cardId': typeof AuthenticatedBookCardIdRoute
  '/creators/apply': typeof AuthenticatedCreatorsApplyRoute
  '/dev/status': typeof AuthenticatedDevStatusRoute
  '/api/public/getaway-prices': typeof ApiPublicGetawayPricesRoute
  '/api/public/getaway-weekly': typeof ApiPublicGetawayWeeklyRoute
  '/api/public/trip-reminders': typeof ApiPublicTripRemindersRoute
  '/api/trip/parse': typeof ApiTripParseRoute
  '/api/trip/price-context': typeof ApiTripPriceContextRoute
  '/api/trip/search': typeof ApiTripSearchRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/getaway-image/$': typeof ApiPublicGetawayImageSplatRoute
  '/api/public/supplier/order-updated': typeof ApiPublicSupplierOrderUpdatedRoute
  '/api/public/calendar/callback/$provider': typeof ApiPublicCalendarCallbackProviderRoute
  '/api/public/calendar/feed/$token': typeof ApiPublicCalendarFeedTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$lang/assistant': typeof LangAssistantRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/business': typeof LangBusinessRoute
  '/creator': typeof AuthenticatedCreatorRoute
  '/credit': typeof AuthenticatedCreditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/getaway': typeof AuthenticatedGetawayRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/c/$handle': typeof CHandleRoute
  '/r/$code': typeof RCodeRoute
  '/$lang': typeof LangIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/admin/getaway': typeof AuthenticatedAdminGetawayRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/book/$cardId': typeof AuthenticatedBookCardIdRoute
  '/creators/apply': typeof AuthenticatedCreatorsApplyRoute
  '/dev/status': typeof AuthenticatedDevStatusRoute
  '/api/public/getaway-prices': typeof ApiPublicGetawayPricesRoute
  '/api/public/getaway-weekly': typeof ApiPublicGetawayWeeklyRoute
  '/api/public/trip-reminders': typeof ApiPublicTripRemindersRoute
  '/api/trip/parse': typeof ApiTripParseRoute
  '/api/trip/price-context': typeof ApiTripPriceContextRoute
  '/api/trip/search': typeof ApiTripSearchRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/getaway-image/$': typeof ApiPublicGetawayImageSplatRoute
  '/api/public/supplier/order-updated': typeof ApiPublicSupplierOrderUpdatedRoute
  '/api/public/calendar/callback/$provider': typeof ApiPublicCalendarCallbackProviderRoute
  '/api/public/calendar/feed/$token': typeof ApiPublicCalendarFeedTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$lang': typeof LangRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/$lang/assistant': typeof LangAssistantRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/business': typeof LangBusinessRoute
  '/_authenticated/creator': typeof AuthenticatedCreatorRoute
  '/_authenticated/credit': typeof AuthenticatedCreditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/getaway': typeof AuthenticatedGetawayRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/c/$handle': typeof CHandleRoute
  '/r/$code': typeof RCodeRoute
  '/$lang/': typeof LangIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/creators': typeof AuthenticatedAdminCreatorsRoute
  '/_authenticated/admin/getaway': typeof AuthenticatedAdminGetawayRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/book/$cardId': typeof AuthenticatedBookCardIdRoute
  '/_authenticated/creators/apply': typeof AuthenticatedCreatorsApplyRoute
  '/_authenticated/dev/status': typeof AuthenticatedDevStatusRoute
  '/api/public/getaway-prices': typeof ApiPublicGetawayPricesRoute
  '/api/public/getaway-weekly': typeof ApiPublicGetawayWeeklyRoute
  '/api/public/trip-reminders': typeof ApiPublicTripRemindersRoute
  '/api/trip/parse': typeof ApiTripParseRoute
  '/api/trip/price-context': typeof ApiTripPriceContextRoute
  '/api/trip/search': typeof ApiTripSearchRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/getaway-image/$': typeof ApiPublicGetawayImageSplatRoute
  '/api/public/supplier/order-updated': typeof ApiPublicSupplierOrderUpdatedRoute
  '/api/public/calendar/callback/$provider': typeof ApiPublicCalendarCallbackProviderRoute
  '/api/public/calendar/feed/$token': typeof ApiPublicCalendarFeedTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/privacy'
    | '/terms'
    | '/$lang/assistant'
    | '/$lang/auth'
    | '/$lang/business'
    | '/creator'
    | '/credit'
    | '/dashboard'
    | '/getaway'
    | '/invoices'
    | '/onboarding'
    | '/plan'
    | '/preferences'
    | '/support'
    | '/trips'
    | '/c/$handle'
    | '/r/$code'
    | '/$lang/'
    | '/admin/analytics'
    | '/admin/creators'
    | '/admin/getaway'
    | '/admin/payments'
    | '/book/$cardId'
    | '/creators/apply'
    | '/dev/status'
    | '/api/public/getaway-prices'
    | '/api/public/getaway-weekly'
    | '/api/public/trip-reminders'
    | '/api/trip/parse'
    | '/api/trip/price-context'
    | '/api/trip/search'
    | '/admin/'
    | '/api/public/getaway-image/$'
    | '/api/public/supplier/order-updated'
    | '/api/public/calendar/callback/$provider'
    | '/api/public/calendar/feed/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/privacy'
    | '/terms'
    | '/$lang/assistant'
    | '/$lang/auth'
    | '/$lang/business'
    | '/creator'
    | '/credit'
    | '/dashboard'
    | '/getaway'
    | '/invoices'
    | '/onboarding'
    | '/plan'
    | '/preferences'
    | '/support'
    | '/trips'
    | '/c/$handle'
    | '/r/$code'
    | '/$lang'
    | '/admin/analytics'
    | '/admin/creators'
    | '/admin/getaway'
    | '/admin/payments'
    | '/book/$cardId'
    | '/creators/apply'
    | '/dev/status'
    | '/api/public/getaway-prices'
    | '/api/public/getaway-weekly'
    | '/api/public/trip-reminders'
    | '/api/trip/parse'
    | '/api/trip/price-context'
    | '/api/trip/search'
    | '/admin'
    | '/api/public/getaway-image/$'
    | '/api/public/supplier/order-updated'
    | '/api/public/calendar/callback/$provider'
    | '/api/public/calendar/feed/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$lang'
    | '/assistant'
    | '/auth'
    | '/business'
    | '/privacy'
    | '/terms'
    | '/$lang/assistant'
    | '/$lang/auth'
    | '/$lang/business'
    | '/_authenticated/creator'
    | '/_authenticated/credit'
    | '/_authenticated/dashboard'
    | '/_authenticated/getaway'
    | '/_authenticated/invoices'
    | '/_authenticated/onboarding'
    | '/_authenticated/plan'
    | '/_authenticated/preferences'
    | '/_authenticated/support'
    | '/_authenticated/trips'
    | '/c/$handle'
    | '/r/$code'
    | '/$lang/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/creators'
    | '/_authenticated/admin/getaway'
    | '/_authenticated/admin/payments'
    | '/_authenticated/book/$cardId'
    | '/_authenticated/creators/apply'
    | '/_authenticated/dev/status'
    | '/api/public/getaway-prices'
    | '/api/public/getaway-weekly'
    | '/api/public/trip-reminders'
    | '/api/trip/parse'
    | '/api/trip/price-context'
    | '/api/trip/search'
    | '/_authenticated/admin/'
    | '/api/public/getaway-image/$'
    | '/api/public/supplier/order-updated'
    | '/api/public/calendar/callback/$provider'
    | '/api/public/calendar/feed/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LangRoute: typeof LangRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  CHandleRoute: typeof CHandleRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicGetawayPricesRoute: typeof ApiPublicGetawayPricesRoute
  ApiPublicGetawayWeeklyRoute: typeof ApiPublicGetawayWeeklyRoute
  ApiPublicTripRemindersRoute: typeof ApiPublicTripRemindersRoute
  ApiTripParseRoute: typeof ApiTripParseRoute
  ApiTripPriceContextRoute: typeof ApiTripPriceContextRoute
  ApiTripSearchRoute: typeof ApiTripSearchRoute
  ApiPublicGetawayImageSplatRoute: typeof ApiPublicGetawayImageSplatRoute
  ApiPublicSupplierOrderUpdatedRoute: typeof ApiPublicSupplierOrderUpdatedRoute
  ApiPublicCalendarCallbackProviderRoute: typeof ApiPublicCalendarCallbackProviderRoute
  ApiPublicCalendarFeedTokenRoute: typeof ApiPublicCalendarFeedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/assistant': {
      id: '/$lang/assistant'
      path: '/assistant'
      fullPath: '/$lang/assistant'
      preLoaderRoute: typeof LangAssistantRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/business': {
      id: '/$lang/business'
      path: '/business'
      fullPath: '/$lang/business'
      preLoaderRoute: typeof LangBusinessRouteImport
      parentRoute: typeof LangRoute
    }
    '/_authenticated/creator': {
      id: '/_authenticated/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof AuthenticatedCreatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credit': {
      id: '/_authenticated/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof AuthenticatedCreditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getaway': {
      id: '/_authenticated/getaway'
      path: '/getaway'
      fullPath: '/getaway'
      preLoaderRoute: typeof AuthenticatedGetawayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$handle': {
      id: '/c/$handle'
      path: '/c/$handle'
      fullPath: '/c/$handle'
      preLoaderRoute: typeof CHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/creators': {
      id: '/_authenticated/admin/creators'
      path: '/admin/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AuthenticatedAdminCreatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/getaway': {
      id: '/_authenticated/admin/getaway'
      path: '/admin/getaway'
      fullPath: '/admin/getaway'
      preLoaderRoute: typeof AuthenticatedAdminGetawayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$cardId': {
      id: '/_authenticated/book/$cardId'
      path: '/book/$cardId'
      fullPath: '/book/$cardId'
      preLoaderRoute: typeof AuthenticatedBookCardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creators/apply': {
      id: '/_authenticated/creators/apply'
      path: '/creators/apply'
      fullPath: '/creators/apply'
      preLoaderRoute: typeof AuthenticatedCreatorsApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/status': {
      id: '/_authenticated/dev/status'
      path: '/dev/status'
      fullPath: '/dev/status'
      preLoaderRoute: typeof AuthenticatedDevStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/getaway-prices': {
      id: '/api/public/getaway-prices'
      path: '/api/public/getaway-prices'
      fullPath: '/api/public/getaway-prices'
      preLoaderRoute: typeof ApiPublicGetawayPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/getaway-weekly': {
      id: '/api/public/getaway-weekly'
      path: '/api/public/getaway-weekly'
      fullPath: '/api/public/getaway-weekly'
      preLoaderRoute: typeof ApiPublicGetawayWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trip-reminders': {
      id: '/api/public/trip-reminders'
      path: '/api/public/trip-reminders'
      fullPath: '/api/public/trip-reminders'
      preLoaderRoute: typeof ApiPublicTripRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip/parse': {
      id: '/api/trip/parse'
      path: '/api/trip/parse'
      fullPath: '/api/trip/parse'
      preLoaderRoute: typeof ApiTripParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip/price-context': {
      id: '/api/trip/price-context'
      path: '/api/trip/price-context'
      fullPath: '/api/trip/price-context'
      preLoaderRoute: typeof ApiTripPriceContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trip/search': {
      id: '/api/trip/search'
      path: '/api/trip/search'
      fullPath: '/api/trip/search'
      preLoaderRoute: typeof ApiTripSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/getaway-image/$': {
      id: '/api/public/getaway-image/$'
      path: '/api/public/getaway-image/$'
      fullPath: '/api/public/getaway-image/$'
      preLoaderRoute: typeof ApiPublicGetawayImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/supplier/order-updated': {
      id: '/api/public/supplier/order-updated'
      path: '/api/public/supplier/order-updated'
      fullPath: '/api/public/supplier/order-updated'
      preLoaderRoute: typeof ApiPublicSupplierOrderUpdatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/callback/$provider': {
      id: '/api/public/calendar/callback/$provider'
      path: '/api/public/calendar/callback/$provider'
      fullPath: '/api/public/calendar/callback/$provider'
      preLoaderRoute: typeof ApiPublicCalendarCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/feed/$token': {
      id: '/api/public/calendar/feed/$token'
      path: '/api/public/calendar/feed/$token'
      fullPath: '/api/public/calendar/feed/$token'
      preLoaderRoute: typeof ApiPublicCalendarFeedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreatorRoute: typeof AuthenticatedCreatorRoute
  AuthenticatedCreditRoute: typeof AuthenticatedCreditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGetawayRoute: typeof AuthenticatedGetawayRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCreatorsRoute: typeof AuthenticatedAdminCreatorsRoute
  AuthenticatedAdminGetawayRoute: typeof AuthenticatedAdminGetawayRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedBookCardIdRoute: typeof AuthenticatedBookCardIdRoute
  AuthenticatedCreatorsApplyRoute: typeof AuthenticatedCreatorsApplyRoute
  AuthenticatedDevStatusRoute: typeof AuthenticatedDevStatusRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreatorRoute: AuthenticatedCreatorRoute,
  AuthenticatedCreditRoute: AuthenticatedCreditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGetawayRoute: AuthenticatedGetawayRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCreatorsRoute: AuthenticatedAdminCreatorsRoute,
  AuthenticatedAdminGetawayRoute: AuthenticatedAdminGetawayRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedBookCardIdRoute: AuthenticatedBookCardIdRoute,
  AuthenticatedCreatorsApplyRoute: AuthenticatedCreatorsApplyRoute,
  AuthenticatedDevStatusRoute: AuthenticatedDevStatusRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LangRouteChildren {
  LangAssistantRoute: typeof LangAssistantRoute
  LangAuthRoute: typeof LangAuthRoute
  LangBusinessRoute: typeof LangBusinessRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAssistantRoute: LangAssistantRoute,
  LangAuthRoute: LangAuthRoute,
  LangBusinessRoute: LangBusinessRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LangRoute: LangRouteWithChildren,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  CHandleRoute: CHandleRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicGetawayPricesRoute: ApiPublicGetawayPricesRoute,
  ApiPublicGetawayWeeklyRoute: ApiPublicGetawayWeeklyRoute,
  ApiPublicTripRemindersRoute: ApiPublicTripRemindersRoute,
  ApiTripParseRoute: ApiTripParseRoute,
  ApiTripPriceContextRoute: ApiTripPriceContextRoute,
  ApiTripSearchRoute: ApiTripSearchRoute,
  ApiPublicGetawayImageSplatRoute: ApiPublicGetawayImageSplatRoute,
  ApiPublicSupplierOrderUpdatedRoute: ApiPublicSupplierOrderUpdatedRoute,
  ApiPublicCalendarCallbackProviderRoute:
    ApiPublicCalendarCallbackProviderRoute,
  ApiPublicCalendarFeedTokenRoute: ApiPublicCalendarFeedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
